# Reference: https://docs.travis-ci.com/user/languages/python/

dist: xenial
sudo: false
language: python
python: "2.7"

branches:
  only:
    - master

addons:
  apt:
    packages:
    - bcftools
    - tabix

install: pip install -r requirements.txt

script: nosetests -v tests
