# Reference: https://docs.travis-ci.com/user/languages/python/

dist: xenial
sudo: false
language: python
python: "2.7"

branches:
  only:
    - master

addons:
  apt:
    packages:
    - bcftools
    - tabix
    - bedtools

before_install:
  - rsync rsync://ftp.ensembl.org/ensembl/pub/grch37/current/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.chromosome.21.fa.gz data/
  - gzip -d data/Homo_sapiens.GRCh37.dna.chromosome.21.fa.gz
  - bgzip data/Homo_sapiens.GRCh37.dna.chromosome.21.fa

env:
  - CMO_RESOURCE_CONFIG=${TRAVIS_BUILD_DIR}/data/cmo_resources.json

install:
  - pip install -r requirements.txt

script:
  - nosetests -v tests
